### ISSUE TITLE
Alternative DRM lock

### ISSUE THREAD

**Issue by sw-username** [Pheeeeenom/fuckigg#10]
There's an alternative DRM: if the bloat is deleted, it gives a rant message about "shit" sites like Skidrow, etc., and the game won't launch at all anymore. You'd have to pretty much redownload the whole thing for the sake of the shortcuts, it's insulting and unacceptable.

Example of game affected:
Moekuri: Adorable + Tactical SRPG (not sure about link policy here in that respect, you can certainly find it at their site). Some other obscure games are affected, as usual.

Unfortunately the wonderful app here won't clear this particular DRM, so would it be possible to extend it's functionality for this? Thanks for everyone's work and for the right attitude.

**Comment by Pheeeeenom** [comment]
I'll have a look at it tonight. I'll start maintaining this program as well

**Comment by Pheeeeenom** [comment]
So it looks like it's just a simple check that can be patched out. In fact, you can simply just launch the game once, then if you set your windows explorer to view hidden files you'll find another copy of the games exe thats approx 4MB~ you can delete the 282KB launcher and all their bloatware and use the main 4MB~ exe to launch Moekuri: Adorable + Tactical SRPG. I'm going to revamp this app and create a database that handles everything so it's easily expandable.

**Comment by sw-username** [comment]
I didn't noticed this easy workaround, thanks a lot for this.
