### ISSUE TITLE
can you maybe add a readme or something that helps you know how to use the program?

### ISSUE THREAD

**Issue by YayJohn** [Pheeeeenom/fuckigg#12]
if not then I have some questions.
what does repack and unpack do? do you use unpack to unpack the zip file? and repack to repack the loose files to an archive?
why would I want to convert tex to png and png to tex?
does sterilize do like the main thing of this program? so I just need to use the sterilize option at the end of the day and thats it?

**Comment by Pheeeeenom** [comment]
I have revamped the way it works. Please check the video in the README

**Comment by YayJohn** [comment]
nice
